### ISSUE TITLE
Update to Julia 1.0

### ISSUE THREAD

**Issue by cossio** [molnarmark/Pastebin.jl#4]
Hello. Are you planning to update this package to Julia 1.0?

**Comment by molnarmark** [comment]
Hi. I have no intention of doing so, I haven't touched Julia code for years now, feel free to fork this repo if you want to continue it.

**Comment by cossio** [comment]
Great, I did a fork: https://github.com/cossio/Pastebin.jl

**Comment by cossio** [comment]
I think this is a nice utility package so I will register it (unless you have any objections).

**Comment by molnarmark** [comment]
Of course, go ahead, no objections.
